"""Prompt Management 迁移 — agent_memory 库

新增三张表：
  1. prompts              — Prompt 元数据（key / name / risk_level / active_version …）
  2. prompt_versions      — 不可变版本行（template / status / change_note …）
  3. prompt_audit_log     — 审计日志（action / actor / detail …）

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-03
"""
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE IF NOT EXISTS public.prompts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key             VARCHAR(128)  NOT NULL,
    name            VARCHAR(256)  NOT NULL DEFAULT '',
    description     TEXT          NOT NULL DEFAULT '',
    category        VARCHAR(64)   NOT NULL DEFAULT '',
    risk_level      VARCHAR(16)   NOT NULL DEFAULT 'low',
    template_engine VARCHAR(32)   NOT NULL DEFAULT 'str_format',
    variables       JSONB         NOT NULL DEFAULT '[]'::jsonb,
    active_version  INTEGER,
    is_code_controlled BOOLEAN    NOT NULL DEFAULT false,
    created_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (key)
);

CREATE INDEX IF NOT EXISTS idx_prompts_key ON public.prompts (key);

CREATE TABLE IF NOT EXISTS public.prompt_versions (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    prompt_id    INTEGER       NOT NULL,
    version      INTEGER       NOT NULL,
    template     TEXT          NOT NULL,
    variables    JSONB         NOT NULL DEFAULT '[]'::jsonb,
    status       VARCHAR(16)   NOT NULL DEFAULT 'draft',
    change_note  TEXT          NOT NULL DEFAULT '',
    created_by   VARCHAR(128)  NOT NULL DEFAULT 'system',
    created_at   TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uq_prompt_version UNIQUE (prompt_id, version),
    CONSTRAINT fk_prompt_versions_prompt
        FOREIGN KEY (prompt_id) REFERENCES public.prompts(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_prompt_versions_prompt_id
    ON public.prompt_versions (prompt_id);

CREATE TABLE IF NOT EXISTS public.prompt_audit_log (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    prompt_key    VARCHAR(128)  NOT NULL,
    action        VARCHAR(32)   NOT NULL,
    from_version  INTEGER,
    to_version    INTEGER,
    actor         VARCHAR(128)  NOT NULL DEFAULT 'system',
    role          VARCHAR(32)   NOT NULL DEFAULT '',
    detail        JSONB,
    created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_prompt_audit_log_key
    ON public.prompt_audit_log (prompt_key);

CREATE SEQUENCE IF NOT EXISTS public.prompts_id_seq
    OWNED BY public.prompts.id;
CREATE SEQUENCE IF NOT EXISTS public.prompt_versions_id_seq
    OWNED BY public.prompt_versions.id;
CREATE SEQUENCE IF NOT EXISTS public.prompt_audit_log_id_seq
    OWNED BY public.prompt_audit_log.id;
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS public.prompt_audit_log CASCADE;")
    op.execute("DROP TABLE IF EXISTS public.prompt_versions CASCADE;")
    op.execute("DROP TABLE IF EXISTS public.prompts CASCADE;")
