"""config — 配置管理（按模块拆分）

.env 加载策略: 从项目根目录 agent/.env 加载（无论 CWD 在哪）。
子模块（database/llm/rag/...）中的 load_dotenv() 会被根 .env 的
值覆盖（override=False），因此只需根 .env 一份配置。
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# 计算项目根目录: config/__init__.py → backend/config/ → backend/ → agent/
_ROOT = Path(__file__).resolve().parent.parent.parent
_ENV_PATH = _ROOT / ".env"
if _ENV_PATH.exists():
    load_dotenv(_ENV_PATH)

# 并发控制
MAX_CONCURRENT_REQUESTS = int(os.getenv("MAX_CONCURRENT_REQUESTS", "5"))

# 安全
API_KEY = os.getenv("API_KEY", "")
CORS_ORIGINS = os.getenv("CORS_ORIGINS", "http://localhost:3000")

# 报告
REPORT_SNAPSHOT_DAYS = int(os.getenv("REPORT_SNAPSHOT_DAYS", "30"))

# SMTP
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.qq.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_FROM = os.getenv("SMTP_FROM", SMTP_USER)

# 通用 settings
from backend.config.settings import (
    LOG_LEVEL,
    LOG_FILE,
    OVERALL_REQUEST_TIMEOUT,
)
# 数据库
from backend.config.database import (
    RAG_DATA_DIR,
    CHUNK_STORE_PATH,
    BM25_INDEX_DIR,
    CHROMA_PATH,
    DOC_DB_PATH,
    DOCS_DIRECTORY,
    DOC_REGISTRY_PATH,
    DOC_OPERATION_LOG_PATH,
    ENABLE_INCREMENTAL_INDEX,
    DB_CONFIG,
    MEMORY_DB_CONFIG,
    BUSINESS_DB_CONFIG,
    BUSINESS_DB_READONLY_CONFIG,
    DB_POOL_MIN_CONN,
    DB_POOL_MAX_CONN,
    DB_CONNECT_TIMEOUT,
    DB_KEEPALIVES_IDLE,
)
# LLM
from backend.config.llm import (
    LLM_MODEL,
    LLM_TEMPERATURE,
    LLM_CONTEXT_LENGTH,
    LLM_MAX_CONCURRENCY,
    LLM_REQUEST_TIMEOUT,
    DEEPSEEK_API_KEY,
    DEEPSEEK_API_BASE,
    MINIMAX_API_KEY,
    MINIMAX_API_BASE,
    EMBEDDING_MODEL_PATH,
    RERANKER_MODEL_PATH,
    RERANK_TIMEOUT,
)
# RAG
from backend.config.rag import (
    CHUNK_SIZE,
    CHUNK_OVERLAP,
    POLICY_MAX_CHUNK_SIZE,
    PROJECT_CHUNK_SIZE,
    GENERAL_CHUNK_SIZE,
    GENERAL_CHUNK_OVERLAP,
    LEAF_CHUNK_TOKENS, PARENT_CHUNK_TOKENS, STRUCTURE_COMPLETE_THRESHOLD,
    ENABLE_SEMANTIC_CHUNKING, ENABLE_LLM_CHUNKING, LLM_CHUNK_MIN_CHARS,
    SEMANTIC_CHUNK_MIN_TOKENS, SEMANTIC_SIMILARITY_THRESHOLD,
    SEMANTIC_EMBED_BATCH_SIZE, SEMANTIC_EMBED_RETRY,
    MAX_CHUNKS_PER_DOC,
    DEFAULT_KB_ID,
    BM25_SEARCH_K,
    HYBRID_SEARCH_K,
    RERANK_TOP_K,
    RERANK_SCORE_THRESHOLD,
    CITATION_SUPPORT_THRESHOLD,
    MULTI_QUERY_MODE,
    MULTI_QUERY_COUNT,
    MULTI_QUERY_TEMPERATURE,
    MULTI_QUERY_MAX_TOKENS,
    MULTI_QUERY_TOP_K_PER,
    MULTI_QUERY_DEDUP,
    MULTI_QUERY_SIMILARITY,
    MULTI_QUERY_MIN_LENGTH,
    ADAPTIVE_CLUSTER_THRESHOLD,
    ADAPTIVE_MAX_CLUSTER_DOCS,
    ADAPTIVE_RETRIEVAL_ENABLED,
    ADAPTIVE_MIN_CHUNKS, ADAPTIVE_K_STEPS,
    KNOWN_PERSON_NAMES,
    DEFAULT_KEYWORDS,
    SIGNAL_RULES,
    DOC_TYPE_RULES,
    DOMAIN_RULES,
    blacklist,
    SUMMARY_MAX_LENGTH,
    TIME_PATTERNS,
    # Faithfulness
    ENABLE_FAITHFULNESS,
    # Evidence Gate（P0）
    EVIDENCE_GATE_ENABLED,
    VEC_MIN_SCORE,
    DOC_TYPE_COVERAGE_REQUIRED,
    GATE_ENTITY_CHECK_ENABLED,
    RERANK_MIN_TOP1,
    RERANK_MIN_AVG,
    RERANK_MIN_GAP,
    RERANK_HIGH_RISK_MIN_TOP1,
    FAITHFULNESS_REJECT_SCORE,
    HIGH_RISK_REJECT_SCORE,
    SELF_CORRECTION_ENABLED,
    SELF_CORRECTION_MAX_RETRIES,
    KNOWLEDGE_GAP_MIN_OCCURRENCES,
    KNOWLEDGE_GAP_WINDOW_HOURS,
)
# Memory
from backend.config.memory import (
    ENABLE_MEMORY,
    ENABLE_HISTORY_AWARE_RETRIEVAL,
    SHORT_TERM_MAX_MESSAGES,
    SESSION_MAX_MESSAGES,
    ENABLE_LONG_TERM_MEMORY,
    L3_PII_FILTER_ENABLED,
    L3_DEDUP_COSINE_THRESHOLD,
    L3_SUPERSEDE_THRESHOLD,
    MEMORY_ASYNC_POOL_SIZE,
    MEMORY_ASYNC_MAX_OVERFLOW,
)
# Logging
from backend.config.logging import (
    LOG_LEVEL as LOG_LEVEL_CFG,  # alias 避免与 settings 冲突
    LOG_FILE as LOG_FILE_CFG,
)
# Storage
from backend.config.storage import (
    STORAGE_CHROMA_PATH,
    STORAGE_BM25_DIR,
    STORAGE_DOCS_DIR,
    STORAGE_DOC_REGISTRY,
)
# RAG 检索器
from backend.config.rag import (
    RERANKER_THRESHOLD,
    ENABLE_PLAN_CRITIQUE,
    ENABLE_RESOURCE_MONITOR,
)
# Cleaners
from backend.config.rag import (
    CLEAN_REMOVE_CONTROL_CHARS,
    CLEAN_NORMALIZE_FULLWIDTH,
    CLEAN_MERGE_BLANK_LINES,
    CLEAN_STRIP_HTML,
    CLEAN_REMOVE_PDF_HEADERS,
    CLEAN_REMOVE_PDF_FOOTERS,
    CLEAN_URL_ACTION,
    CLEAN_EMAIL_ACTION,
    FILTER_MIN_CHUNK_LENGTH,
    FILTER_MAX_SYMBOL_RATIO,
    FILTER_MIN_CHINESE_RATIO,
    FILTER_SIMHASH_THRESHOLD,
    FILTER_ENABLE_PII_MASK,
)
# Faithfulness (NLI answer verification)
from backend.config.rag import (
    ENABLE_FAITHFULNESS, FAITHFULNESS_SKIP_THRESHOLD, NLI_USE_LLM,
)

__all__ = [
    # settings
    "LOG_LEVEL", "LOG_FILE", "OVERALL_REQUEST_TIMEOUT",
    # database
    "RAG_DATA_DIR", "CHUNK_STORE_PATH",
    "BM25_INDEX_DIR", "CHROMA_PATH", "DOC_DB_PATH", "DOCS_DIRECTORY",
    "DOC_REGISTRY_PATH", "DOC_OPERATION_LOG_PATH", "ENABLE_INCREMENTAL_INDEX", "DB_CONFIG", "MEMORY_DB_CONFIG", "BUSINESS_DB_CONFIG",
    "BUSINESS_DB_READONLY_CONFIG", "DB_POOL_MIN_CONN", "DB_POOL_MAX_CONN", "DB_CONNECT_TIMEOUT", "DB_KEEPALIVES_IDLE",
    # llm
    "LLM_MODEL", "LLM_TEMPERATURE", "LLM_CONTEXT_LENGTH", "LLM_MAX_CONCURRENCY",
    "LLM_REQUEST_TIMEOUT", "DEEPSEEK_API_KEY", "DEEPSEEK_API_BASE",
    "MINIMAX_API_KEY", "MINIMAX_API_BASE", "EMBEDDING_MODEL_PATH",
    "RERANKER_MODEL_PATH", "RERANK_TIMEOUT",
    # rag
    "CHUNK_SIZE", "CHUNK_OVERLAP", "PROJECT_CHUNK_SIZE",
    "POLICY_MAX_CHUNK_SIZE", "GENERAL_CHUNK_SIZE", "GENERAL_CHUNK_OVERLAP",
    "LEAF_CHUNK_TOKENS", "PARENT_CHUNK_TOKENS", "STRUCTURE_COMPLETE_THRESHOLD",
    "ENABLE_SEMANTIC_CHUNKING", "ENABLE_LLM_CHUNKING", "LLM_CHUNK_MIN_CHARS",
    "SEMANTIC_CHUNK_MIN_TOKENS", "SEMANTIC_SIMILARITY_THRESHOLD",
    "SEMANTIC_EMBED_BATCH_SIZE", "SEMANTIC_EMBED_RETRY",
    "MAX_CHUNKS_PER_DOC",
    "DEFAULT_KB_ID",
    "BM25_SEARCH_K", "HYBRID_SEARCH_K", "RERANK_TOP_K",
    "RERANK_SCORE_THRESHOLD", "CITATION_SUPPORT_THRESHOLD",
    "MULTI_QUERY_MODE", "MULTI_QUERY_COUNT", "MULTI_QUERY_TEMPERATURE",
    "MULTI_QUERY_MAX_TOKENS", "MULTI_QUERY_TOP_K_PER", "MULTI_QUERY_DEDUP",
    "MULTI_QUERY_SIMILARITY", "MULTI_QUERY_MIN_LENGTH",
    "ADAPTIVE_CLUSTER_THRESHOLD", "ADAPTIVE_MAX_CLUSTER_DOCS",
    "ADAPTIVE_RETRIEVAL_ENABLED",
    "ADAPTIVE_MIN_CHUNKS", "ADAPTIVE_K_STEPS",
    "KNOWN_PERSON_NAMES", "DEFAULT_KEYWORDS", "SIGNAL_RULES",
    "DOC_TYPE_RULES", "DOMAIN_RULES", "blacklist",
    "SUMMARY_MAX_LENGTH", "TIME_PATTERNS",
    "RERANKER_THRESHOLD", "ENABLE_PLAN_CRITIQUE", "ENABLE_RESOURCE_MONITOR",
    # memory
    "ENABLE_MEMORY", "ENABLE_HISTORY_AWARE_RETRIEVAL",
    "SHORT_TERM_MAX_MESSAGES", "SESSION_MAX_MESSAGES",
    "ENABLE_LONG_TERM_MEMORY", "L3_PII_FILTER_ENABLED",
    "L3_DEDUP_COSINE_THRESHOLD", "L3_SUPERSEDE_THRESHOLD",
    "MEMORY_ASYNC_POOL_SIZE", "MEMORY_ASYNC_MAX_OVERFLOW",
    # storage
    "STORAGE_CHROMA_PATH", "STORAGE_BM25_DIR", "STORAGE_DOCS_DIR",
    "STORAGE_DOC_REGISTRY",
    # cleaner/filter
    "CLEAN_REMOVE_CONTROL_CHARS", "CLEAN_NORMALIZE_FULLWIDTH",
    "CLEAN_MERGE_BLANK_LINES", "CLEAN_STRIP_HTML",
    "CLEAN_REMOVE_PDF_HEADERS", "CLEAN_REMOVE_PDF_FOOTERS",
    "CLEAN_URL_ACTION", "CLEAN_EMAIL_ACTION",
    "FILTER_MIN_CHUNK_LENGTH", "FILTER_MAX_SYMBOL_RATIO",
    "FILTER_MIN_CHINESE_RATIO", "FILTER_SIMHASH_THRESHOLD",
    "FILTER_ENABLE_PII_MASK",
    # faithfulness
    "ENABLE_FAITHFULNESS", "FAITHFULNESS_SKIP_THRESHOLD", "NLI_USE_LLM",
    # email
    "SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "SMTP_FROM",
]