"""config — 配置管理（按模块拆分）

.env 加载策略: 优先项目根目录 agent/.env，其次 backend/.env（无论 CWD 在哪）。
子模块（database/llm/rag/...）中的 load_dotenv() 不会被后加载的 .env 值
覆盖（override=False），因此只需一份配置。
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# 计算项目根目录: config/__init__.py → backend/config/ → backend/ → agent/
_ROOT = Path(__file__).resolve().parent.parent.parent
_BACKEND_DIR = _ROOT / "backend"
# 必须在下方读取任何 os.getenv 之前加载（否则 API_KEY/ALLOW_UNAUTHENTICATED 等
# 会拿到未填充的空值，导致 auth 中间件误判 fail-closed）。override=False：
# 先加载的根 .env 优先，子模块的 load_dotenv() 不会覆盖。
for _env_path in (_ROOT / ".env", _BACKEND_DIR / ".env"):
    if _env_path.exists():
        load_dotenv(_env_path)

# 运行环境（fail-safe: 无法识别时按 production 处理，拒绝降级到宽松策略）
_VALID_ENVIRONMENTS = {"development", "testing", "staging", "production"}
ENVIRONMENT = os.getenv("ENVIRONMENT", "development").strip().lower()
if ENVIRONMENT not in _VALID_ENVIRONMENTS:
    ENVIRONMENT = "production"

# 并发控制
MAX_CONCURRENT_REQUESTS = int(os.getenv("MAX_CONCURRENT_REQUESTS", "5"))
# 优先级排队：槽位满时高优先级请求（对话）进等待队列而不是立刻 503，
# 低优先级（上传/重索引/导出）几乎不等待直接拒绝。0 表示禁用排队（恢复纯 503）。
CONCURRENCY_QUEUE_TIMEOUT = float(os.getenv("CONCURRENCY_QUEUE_TIMEOUT", "10"))

# 分布式准入门（2026-09-30 主架构改造 P0-1）：Redis 全局硬上限，多副本共享。
# 进程内 _PriorityGate 只管单副本，扩 N 副本实际放行 N×MAX_CONCURRENT_REQUESTS；
# 本门用 Redis sorted set 槽位补全局口径。分层语义：本门=硬上限无等待队列
# （满即 503+Retry-After），排队/优先级仍由进程内门承担；Redis 不可用
# fail-open 放行（进程内门兜底）。默认 false——关闭时零 Redis 访问、行为与主线一致。
DIST_CONCURRENCY_ENABLED = os.getenv("DIST_CONCURRENCY_ENABLED", "false").strip().lower() in ("1", "true", "yes")
# 全局并发上限（跨全部副本合计）
DIST_MAX_CONCURRENT_REQUESTS = int(os.getenv("DIST_MAX_CONCURRENT_REQUESTS", "50"))
# 槽位租约 TTL（秒）：持槽进程崩溃后，过期槽位由后续 acquire 顺带回收
DIST_GATE_LEASE_TTL_SECONDS = int(os.getenv("DIST_GATE_LEASE_TTL_SECONDS", "30"))
# 租户级上限（按 JWT tenant_id claim 分桶，与全局上限叠加判定）；0=不启用
DIST_TENANT_MAX_CONCURRENT = int(os.getenv("DIST_TENANT_MAX_CONCURRENT", "0"))

# 工具统计多副本聚合（P1-4，2026-09-30）：管理端 /admin/tools/stats 原为进程内
# Prometheus 直读（scope=process），多副本数字不完整。写侧开关开启后
# record_tool_result 旁路向 Redis 日键 HINCRBY（tool:total/ok/七分类错误码，
# TTL 8 天，fire-and-forget 软失败，不阻塞工具热路径）；读侧按 source 取数：
# process=仅进程内（默认，行为零变化）| redis=仅 Redis 合计 | merged=两者相加。
TOOL_STATS_REDIS_ENABLED = os.getenv("TOOL_STATS_REDIS_ENABLED", "false").strip().lower() in ("1", "true", "yes")
TOOL_STATS_SOURCE = os.getenv("TOOL_STATS_SOURCE", "process").strip().lower()
if TOOL_STATS_SOURCE not in ("process", "redis", "merged"):
    TOOL_STATS_SOURCE = "process"

# 安全
API_KEY = os.getenv("API_KEY", "")
# 显式豁免认证（仅限本地开发调试；生产环境禁止开启）
ALLOW_UNAUTHENTICATED = os.getenv("ALLOW_UNAUTHENTICATED", "false").strip().lower() in ("1", "true", "yes")
CORS_ORIGINS = os.getenv("CORS_ORIGINS", "http://localhost:3000")

# SQL 数据安全（P1-11）
# 信任网关注入的用户身份头：仅当反向代理/网关已完成认证并注入该头时开启。
# 开启后 /sql 路由从该头推导 current_user_id（行级安全参数），忽略请求体中的同名
# 字段（客户端不可伪造）；关闭时 user_id 恒为 None。
TRUST_USER_HEADER = os.getenv("TRUST_USER_HEADER", "false").strip().lower() in ("1", "true", "yes")
USER_ID_HEADER = os.getenv("USER_ID_HEADER", "X-User-Id")
# 行级安全总开关：默认关闭（Demo 查询不携带用户上下文，严格模式会全部拒绝）。
# 生产开启后，schema_config.row_security 中配置的表将强制按用户隔离。
SQL_ROW_SECURITY_ENABLED = os.getenv("SQL_ROW_SECURITY_ENABLED", "false").strip().lower() in ("1", "true", "yes")
# SQL Agent 生产 kill switch（2026-09-23 STOP C）：关闭时全部 SQL 生产入口
# （HTTP /sql*、图内 SQLSkill、Tool、MCP）返回服务不可用，executor 零调用。
# 默认 true——SQL Agent 是存量生产功能，开关只作应急停用，不改变现网行为。
# 注意语义：不可用 ≠ 权限拒绝（error_type=service_unavailable，避免误导权限诊断）。
SQL_AGENT_ENABLED = os.getenv("SQL_AGENT_ENABLED", "true").strip().lower() in ("1", "true", "yes")

# 报告
REPORT_SNAPSHOT_DAYS = int(os.getenv("REPORT_SNAPSHOT_DAYS", "30"))

# SMTP
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.qq.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_FROM = os.getenv("SMTP_FROM", SMTP_USER)

# 邮件引擎（批次1 Skill 集成）：smtp = 传统 SMTP 发送（仅 email.send）；
# agently = QQ 邮箱 Agently Mail CLI（agently-cli，支持收/搜/读/监听）。
# 引擎只影响发送路径；search/read/watch 三个读能力仅 agently 引擎提供。
EMAIL_ENGINE = os.getenv("EMAIL_ENGINE", "smtp").strip().lower()
# agently-cli 二进制名（PATH 中查找）；watch 长轮询单次上限（秒）
AGENTLY_BIN = os.getenv("AGENTLY_BIN", "agently-cli")
AGENTLY_WATCH_MAX_SECONDS = int(os.getenv("AGENTLY_WATCH_MAX_SECONDS", "300"))


# Tool 审批门（写操作工具的 human-in-the-loop）
# required: 写操作需人工审批后执行（默认，企业安全基线）
# auto:     跳过审批直接执行（仅本地开发调试）
TOOL_APPROVAL_MODE = os.getenv("TOOL_APPROVAL_MODE", "required").strip().lower()
if TOOL_APPROVAL_MODE not in ("required", "auto"):
    TOOL_APPROVAL_MODE = "required"
# 已批准审批单的有效期（秒）：批准后需在 TTL 内重试相同操作才放行
TOOL_APPROVAL_TTL_SECONDS = int(os.getenv("TOOL_APPROVAL_TTL_SECONDS", "600"))

# MCP 工具调用超时（秒）— manager.route 无超时会挂死协议端点
MCP_TOOL_TIMEOUT = int(os.getenv("MCP_TOOL_TIMEOUT", "60"))

# 主图 LangGraph 保护
# 递归上限：supervisor 最多 10 轮 × (调度+执行) + 规划/审查/汇总 ≈ 25 超步，
# 取 80 留余量（超限 LangGraph 抛 GraphRecursionError 而非静默挂起）
MAIN_GRAPH_RECURSION_LIMIT = int(os.getenv("MAIN_GRAPH_RECURSION_LIMIT", "80"))
# 主图 checkpointer（默认关：开启后 request_context 以 checkpoint 安全 dict 进状态，
# Send 并行分支的流式/trace 绑定降级 — 见 orchestration/request_context.py）
MAIN_GRAPH_CHECKPOINTER_ENABLED = os.getenv("MAIN_GRAPH_CHECKPOINTER_ENABLED", "false").strip().lower() in ("1", "true", "yes")

# 状态键登记守卫（P1-1，2026-09-30）：节点 update 写入未登记 schema 的键会被
# LangGraph updates 流与 state 双静默剥离（历史事故 ×4）。log = warning +
# state_unknown_key_total 指标（默认，行为零变化）；enforce = 抛错（测试/预发
# 验证用）。发现未知键的正确修法是补登记进 state.py，不接受 exclude 黑名单。
STATE_KEY_GUARD_MODE = os.getenv("STATE_KEY_GUARD_MODE", "log").strip().lower()
if STATE_KEY_GUARD_MODE not in ("log", "enforce"):
    STATE_KEY_GUARD_MODE = "log"

# OTel 第二出口（P2-3，2026-09-30）：自研 trace（PG 存储）保持权威不变，
# 开启时每个 span 收口镜像一份到 OTLP collector（BatchSpanProcessor 后台
# 异步导出，失败仅 debug 不影响主链路）。双条件启用：总开关默认关 +
# 标准 OTLP endpoint 已配置。零新增依赖（sdk/exporter 已在锁文件 1.41.1）。
OTEL_TRACE_OTLP_ENABLED = os.getenv("OTEL_TRACE_OTLP_ENABLED", "false").strip().lower() in ("1", "true", "yes")
OTEL_EXPORTER_OTLP_ENDPOINT = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "").strip().rstrip("/")

# 拒答转追问（2026-09-19）：L1 入口弱命中追问 + L2 拒答后业务导航追问。
# 关闭即回滚为纯拒答行为；追问内容与接线见 orchestration/graph/clarify_content.py
REFUSAL_CLARIFY_ENABLED = os.getenv("REFUSAL_CLARIFY_ENABLED", "true").strip().lower() in ("1", "true", "yes")

# 通用 settings
from backend.config.settings import (
    LOG_LEVEL,
    LOG_FILE,
    OVERALL_REQUEST_TIMEOUT,
)
# 数据库
from backend.config.database import (
    RAG_DATA_DIR,
    CHUNK_STORE_PATH,
    BM25_INDEX_DIR,
    CHROMA_PATH,
    DOC_DB_PATH,
    DOCS_DIRECTORY,
    DOC_REGISTRY_PATH,
    DOC_OPERATION_LOG_PATH,
    ENABLE_INCREMENTAL_INDEX,
    DB_CONFIG,
    MEMORY_DB_CONFIG,
    BUSINESS_DB_CONFIG,
    BUSINESS_DB_READONLY_CONFIG,
    DB_POOL_MIN_CONN,
    DB_POOL_MAX_CONN,
    DB_CONNECT_TIMEOUT,
    DB_KEEPALIVES_IDLE,
)
# LLM
from backend.config.llm import (
    ENV_MODE,
    EMBEDDING_PROVIDER,
    RERANK_PROVIDER,
    OLLAMA_ENABLED,
    OLLAMA_BASE_URL,
    OLLAMA_MODEL,
    OLLAMA_KEEP_ALIVE,
    EMBEDDING_MODEL,
    EMBEDDING_API_BASE,
    EMBEDDING_API_KEY,
    EMBEDDING_MODEL_PATH,
    EMBEDDING_BATCH_SIZE,
    EMBEDDING_REQUEST_TIMEOUT,
    RERANK_MODEL,
    RERANK_API_FORMAT,
    RERANK_BASE_URL,
    RERANKER_MODEL_PATH,
    RERANK_TIMEOUT,
    TOKEN_USAGE_LOG_PATH,
    EVAL_DATASET_PATH,
    LLM_MODEL,
    LLM_TEMPERATURE,
    LLM_CONTEXT_LENGTH,
    LLM_MAX_CONCURRENCY,
    LLM_REQUEST_TIMEOUT,
    ROUTER_LLM_TIMEOUT,
    ROUTER_LLM_MAX_TOKENS,
    PLANNER_LLM_MAX_TOKENS,
    ENABLE_TOKEN_STREAMING,
    LLM_STREAM_USAGE,
    ENABLE_FC_TOOL_SELECTION,
    TOOL_SELECTOR_LLM_TIMEOUT,
    TOOL_SELECTOR_LLM_MAX_TOKENS,
    TOOL_SELECTOR_MODEL,
    FC_TOOL_SELECTION_ROLLOUT_PERCENT,
    FC_TOOL_SELECTION_ALLOWLIST,
    TOOL_SELECTOR_FAST_PATH_SCORE,
    TOOL_SELECTOR_MAX_CANDIDATES,
    COARSE_DOMAIN_CONFIDENCE,
    COARSE_DOMAIN_MIN_MARGIN,
    COARSE_RULE_STRONG_HITS,
    COARSE_RULE_HINT_BONUS,
    COARSE_SOFTMAX_TEMP,
    FINE_TOOL_HIGH_CONFIDENCE,
    FINE_TOOL_MIN_MARGIN,
    DEEPSEEK_API_KEY,
    DEEPSEEK_API_BASE,
    MINIMAX_API_KEY,
    MINIMAX_API_BASE,
    QWEN_API_KEY,
    QWEN_API_BASE,
    QWEN_TP_API_KEY,
    QWEN_TP_API_BASE,
    VLLM_API_KEY,
    VLLM_API_BASE,
    SILICONFLOW_API_KEY,
    SILICONFLOW_API_BASE,
)
# RAG
from backend.config.rag import (
    CHUNK_SIZE,
    CHUNK_OVERLAP,
    LEAF_CHUNK_TOKENS, PARENT_CHUNK_TOKENS, STRUCTURE_COMPLETE_THRESHOLD,
    ENABLE_SEMANTIC_CHUNKING,
    SEMANTIC_CHUNK_MIN_TOKENS, SEMANTIC_SIMILARITY_THRESHOLD,
    SEMANTIC_EMBED_BATCH_SIZE, SEMANTIC_EMBED_RETRY,
    ENABLE_SIMULATED_QUESTIONS, QUESTION_GEN_MAX_CHUNKS,
    ENABLE_TABLE_DESCRIPTIONS, TABLE_DESC_MAX_ROWS,
    LEGAL_CLAUSES_PER_PARENT,
    EMBED_BATCH_SIZE,
    MAX_CHUNKS_PER_DOC,
    DEFAULT_KB_ID,
    VECTOR_PG_POOL_MIN,
    VECTOR_PG_POOL_MAX,
    VECTOR_HNSW_EF_SEARCH,
    RAG_DOC_CANDIDATE_K,
    BM25_SEARCH_K,
    BM25_CANDIDATE_K,
    HYBRID_SEARCH_K,
    RERANK_TOP_K,
    RERANK_SCORE_THRESHOLD,
    RERANKER_DEVICE,
    CITATION_SUPPORT_THRESHOLD,
    MULTI_QUERY_MODE,
    MULTI_QUERY_COUNT,
    MULTI_QUERY_TEMPERATURE,
    MULTI_QUERY_MAX_TOKENS,
    MULTI_QUERY_TOP_K_PER,
    MULTI_QUERY_DEDUP,
    MULTI_QUERY_SIMILARITY,
    MULTI_QUERY_MIN_LENGTH,
    EVIDENCE_TOKEN_BUDGET,
    ADAPTIVE_CLUSTER_THRESHOLD,
    ADAPTIVE_MAX_CLUSTER_DOCS,
    ADAPTIVE_RETRIEVAL_ENABLED,
    ADAPTIVE_MIN_CHUNKS, ADAPTIVE_K_STEPS,
    KNOWN_PERSON_NAMES,
    DEFAULT_KEYWORDS,
    SIGNAL_RULES,
    DOC_TYPE_RULES,
    DOMAIN_RULES,
    blacklist,
    SUMMARY_MAX_LENGTH,
    TIME_PATTERNS,
    # Faithfulness
    ENABLE_FAITHFULNESS,
    # Evidence Gate（P0）
    EVIDENCE_GATE_ENABLED,
    VEC_MIN_SCORE,
    DOC_TYPE_COVERAGE_REQUIRED,
    GATE_ENTITY_CHECK_ENABLED,
    RERANK_MIN_TOP1,
    RERANK_MIN_AVG,
    RERANK_MIN_GAP,
    RERANK_HIGH_RISK_MIN_TOP1,
    FAITHFULNESS_REJECT_SCORE,
    HIGH_RISK_REJECT_SCORE,
    SELF_CORRECTION_ENABLED,
    SELF_CORRECTION_MAX_RETRIES,
    KNOWLEDGE_GAP_MIN_OCCURRENCES,
    KNOWLEDGE_GAP_WINDOW_HOURS,
)
# Memory
from backend.config.memory import (
    ENABLE_MEMORY,
    ENABLE_HISTORY_AWARE_RETRIEVAL,
    SHORT_TERM_MAX_MESSAGES,
    HISTORY_TOKEN_BUDGET,
    SESSION_MAX_MESSAGES,
    # L2 摘要滞后门（STOP E）
    CONTEXT_L2_SUMMARY_MIN_DELTA_MESSAGES,
    ENABLE_LONG_TERM_MEMORY,
    L3_PII_FILTER_ENABLED,
    L3_DEDUP_COSINE_THRESHOLD,
    L3_SUPERSEDE_THRESHOLD,
    # 记忆 provenance（047，STOP B）
    MEMORY_ORIGIN_EXPLICIT,
    MEMORY_ORIGIN_INFERRED,
    MEMORY_ORIGIN_LEGACY,
    MEMORY_EXPLICIT_DEFAULT_CONFIDENCE,
    MEMORY_INFERRED_DEFAULT_CONFIDENCE,
    MEMORY_HEDGED_CONFIDENCE_CAP,
    # L3 读取管线（STOP D）
    MEMORY_RETRIEVAL_CANDIDATES,
    MEMORY_MAX_INJECTED,
    MEMORY_MIN_RELEVANCE_SCORE,
    MEMORY_GLOBAL_KEY_PREFIXES,
    MEMORY_MAX_GLOBAL_PREFERENCES,
    MEMORY_ASYNC_POOL_SIZE,
    MEMORY_ASYNC_MAX_OVERFLOW,
    # 上下文预算管理（Context Budget Management，2026-09-22）
    CONTEXT_BUDGET_ENABLED,
    CONTEXT_OUTPUT_RESERVE_TOKENS,
    CONTEXT_SAFETY_RESERVE_TOKENS,
    TOOL_INLINE_MAX_TOKENS,
    TOOL_PREVIEW_MAX_TOKENS,
    PREVIOUS_OUTPUTS_MAX_TOKENS,
    CONTEXT_L4_TRIGGER_RATIO,
    CONTEXT_L4_TARGET_RATIO,
    CONTEXT_L5_TRIGGER_RATIO,
    CONTEXT_L4_KEEP_RECENT_TURNS,
    CONTEXT_L5_ENABLED,
    CONTEXT_L5_TARGET_RATIO,
    CONTEXT_L5_SUMMARY_TIMEOUT_SECONDS,
    CONTEXT_L5_ONLINE_WAIT_SECONDS,
    CONTEXT_L5_SUMMARY_MODEL,
    CONTEXT_L5_SUMMARY_MAX_TOKENS,
    CONTEXT_L5_SUMMARY_TEMPERATURE,
    CONTEXT_L5_MIN_DELTA_MESSAGES,
    CONTEXT_L5_MAX_DELTA_MESSAGES,
    CONTEXT_L5_MAX_PROTECTED_FACTS,
    CONTEXT_L5_LOCK_TTL,
    CONTEXT_TOKEN_ESTIMATION_MARGIN,
    CONTEXT_IMAGE_TOKEN_ESTIMATE,
    CONTEXT_MESSAGE_OVERHEAD_TOKENS,
)
# Logging
from backend.config.logging import (
    LOG_LEVEL as LOG_LEVEL_CFG,  # alias 避免与 settings 冲突
    LOG_FILE as LOG_FILE_CFG,
)
# Storage
from backend.config.storage import (
    STORAGE_CHROMA_PATH,
    STORAGE_BM25_DIR,
    STORAGE_DOCS_DIR,
    STORAGE_DOC_REGISTRY,
)
# RAG 检索器
from backend.config.rag import (
    RERANKER_THRESHOLD,
    ENABLE_PLAN_CRITIQUE,
    ENABLE_RESOURCE_MONITOR,
    RAG_ANSWER_CACHE_ENABLED,
)
# Cleaners
from backend.config.rag import (
    CLEAN_REMOVE_CONTROL_CHARS,
    CLEAN_NORMALIZE_FULLWIDTH,
    CLEAN_MERGE_BLANK_LINES,
    CLEAN_STRIP_HTML,
    CLEAN_REMOVE_PDF_HEADERS,
    CLEAN_REMOVE_PDF_FOOTERS,
    CLEAN_URL_ACTION,
    CLEAN_EMAIL_ACTION,
    FILTER_MIN_CHUNK_LENGTH,
    FILTER_MAX_SYMBOL_RATIO,
    FILTER_MIN_CHINESE_RATIO,
    FILTER_SIMHASH_THRESHOLD,
    FILTER_ENABLE_PII_MASK,
    # Financial tables
    FINANCIAL_TABLE_ROWS_PER_CHUNK,
    FINANCIAL_MAX_CHUNKS_PER_DOC,
    FINANCIAL_PII_MASK_FORCE,
    FINANCIAL_SQL_BYPASS_ENABLED,
    FINANCIAL_METRIC_PATTERNS,
    FINANCIAL_NUMERIC_CONDITION_RE,
    FINANCIAL_NUMERIC_CONDITION_RE_LTE,
    FINANCIAL_PII_PATTERNS,
)
# Faithfulness (NLI answer verification)
from backend.config.rag import (
    ENABLE_FAITHFULNESS, FAITHFULNESS_SKIP_THRESHOLD, NLI_USE_LLM,
)
# Input Guard（输入侧安全门禁）
from backend.config import guard  # noqa: F401 — 模块形式暴露（backend.config.guard.XXX）
from backend.config.chat_input import (  # noqa: F401 — 聊天输入限制（单一来源）
    CHAT_INPUT_MAX_CHARS,
    CHAT_INPUT_MAX_BYTES,
    CHAT_INPUT_MAX_TOKENS,
)
# Customer Service（客服子系统）
from backend.config.customer_service import (
    CS_ENABLED,
    CS_CONFIRMATION_TTL_SECONDS,
    CS_HANDOFF_TIMEOUT_SECONDS,
    CS_MAX_CONFIRMATION_RETRIES,
    CS_HIGH_RISK_ACTIONS,
    CS_CRITICAL_ACTIONS,
    CS_KNOWLEDGE_BASES,
    COMPLAINT_PATTERNS,
    CS_DOMAIN_KEYWORDS,
    CS_DOMAIN_PATTERNS,
    CS_RULE_MIN_HITS,
    CS_CONFIDENCE_ANSWER,
    CS_CONFIDENCE_CAUTIOUS,
    CS_GRAPH_ENABLED,
    CS_EXPERT_MAX_LOOPS,
    CS_SUPERVISOR_LLM_ENABLED,
    CS_SUPERVISOR_LLM_TIMEOUT_MS,
    CS_CHECKPOINTER_ENABLED,
    CS_GRAPH_RECURSION_LIMIT,
)
# Redis
from backend.config.redis import (
    REDIS_ENABLED,
    REDIS_URL,
    REDIS_KEY_PREFIX,
    REDIS_MAX_CONNECTIONS,
    REDIS_SOCKET_TIMEOUT,
)
# Observability (trace redaction / sampling / PG mirror)
from backend.config.observability import (
    TRACE_PII_MASKING_ENABLED,
    TRACE_DETAIL_LEVEL,
    TRACE_SAMPLING_RATE,
    TRACE_PG_MIRROR_ENABLED,
)

__all__ = [
    # environment
    "ENVIRONMENT",
    # settings
    "LOG_LEVEL", "LOG_FILE", "OVERALL_REQUEST_TIMEOUT",
    # sql 数据安全
    "TRUST_USER_HEADER", "USER_ID_HEADER", "SQL_ROW_SECURITY_ENABLED",
    "SQL_AGENT_ENABLED",
    # tool 审批门 / MCP / 主图保护 / 状态键守卫
    "TOOL_APPROVAL_MODE", "TOOL_APPROVAL_TTL_SECONDS", "MCP_TOOL_TIMEOUT",
    "MAIN_GRAPH_RECURSION_LIMIT", "MAIN_GRAPH_CHECKPOINTER_ENABLED",
    "STATE_KEY_GUARD_MODE",
    # OTel 第二出口（P2-3）
    "OTEL_TRACE_OTLP_ENABLED", "OTEL_EXPORTER_OTLP_ENDPOINT",
    # 拒答转追问
    "REFUSAL_CLARIFY_ENABLED",
    # 并发控制 / 分布式准入门
    "MAX_CONCURRENT_REQUESTS", "CONCURRENCY_QUEUE_TIMEOUT",
    "DIST_CONCURRENCY_ENABLED", "DIST_MAX_CONCURRENT_REQUESTS",
    "DIST_GATE_LEASE_TTL_SECONDS", "DIST_TENANT_MAX_CONCURRENT",
    # 工具统计多副本聚合
    "TOOL_STATS_REDIS_ENABLED", "TOOL_STATS_SOURCE",
    # database
    "RAG_DATA_DIR", "CHUNK_STORE_PATH",
    "BM25_INDEX_DIR", "CHROMA_PATH", "DOC_DB_PATH", "DOCS_DIRECTORY",
    "DOC_REGISTRY_PATH", "DOC_OPERATION_LOG_PATH", "ENABLE_INCREMENTAL_INDEX", "DB_CONFIG", "MEMORY_DB_CONFIG", "BUSINESS_DB_CONFIG",
    "BUSINESS_DB_READONLY_CONFIG", "DB_POOL_MIN_CONN", "DB_POOL_MAX_CONN", "DB_CONNECT_TIMEOUT", "DB_KEEPALIVES_IDLE",
    # llm
    "LLM_MODEL", "LLM_TEMPERATURE", "LLM_CONTEXT_LENGTH", "LLM_MAX_CONCURRENCY",
    "LLM_REQUEST_TIMEOUT", "DEEPSEEK_API_KEY", "DEEPSEEK_API_BASE",
    "MINIMAX_API_KEY", "MINIMAX_API_BASE", "QWEN_API_KEY", "QWEN_API_BASE",
    "QWEN_TP_API_KEY", "QWEN_TP_API_BASE",
    "VLLM_API_KEY", "VLLM_API_BASE", "SILICONFLOW_API_KEY", "SILICONFLOW_API_BASE",
    "EMBEDDING_BATCH_SIZE", "EMBEDDING_REQUEST_TIMEOUT",
    "EMBEDDING_PROVIDER", "RERANK_PROVIDER",
    "RERANK_API_FORMAT", "RERANK_BASE_URL",
    "ENABLE_FC_TOOL_SELECTION", "TOOL_SELECTOR_LLM_TIMEOUT",
    "TOOL_SELECTOR_LLM_MAX_TOKENS",
    "TOOL_SELECTOR_MODEL", "FC_TOOL_SELECTION_ROLLOUT_PERCENT",
    "FC_TOOL_SELECTION_ALLOWLIST",
    "TOOL_SELECTOR_FAST_PATH_SCORE", "TOOL_SELECTOR_MAX_CANDIDATES",
    "COARSE_DOMAIN_CONFIDENCE", "COARSE_DOMAIN_MIN_MARGIN",
    "COARSE_RULE_STRONG_HITS", "COARSE_RULE_HINT_BONUS",
    "COARSE_SOFTMAX_TEMP",
    "FINE_TOOL_HIGH_CONFIDENCE", "FINE_TOOL_MIN_MARGIN",
    "EMBEDDING_MODEL_PATH",
    "RERANKER_MODEL_PATH", "RERANK_TIMEOUT", "EVAL_DEVICE",
    # rag
    "CHUNK_SIZE", "CHUNK_OVERLAP",
        "LEAF_CHUNK_TOKENS", "PARENT_CHUNK_TOKENS", "STRUCTURE_COMPLETE_THRESHOLD",
    "ENABLE_SEMANTIC_CHUNKING",
    "SEMANTIC_CHUNK_MIN_TOKENS", "SEMANTIC_SIMILARITY_THRESHOLD",
    "SEMANTIC_EMBED_BATCH_SIZE", "SEMANTIC_EMBED_RETRY",
    "ENABLE_SIMULATED_QUESTIONS", "QUESTION_GEN_MAX_CHUNKS",
    "ENABLE_TABLE_DESCRIPTIONS", "TABLE_DESC_MAX_ROWS",
    "LEGAL_CLAUSES_PER_PARENT",
    "EMBED_BATCH_SIZE",
    "MAX_CHUNKS_PER_DOC",
    "DEFAULT_KB_ID",
    "VECTOR_PG_POOL_MIN", "VECTOR_PG_POOL_MAX", "VECTOR_HNSW_EF_SEARCH",
    "RAG_DOC_CANDIDATE_K", "BM25_SEARCH_K", "BM25_CANDIDATE_K",
    "HYBRID_SEARCH_K", "RERANK_TOP_K",
    "RERANK_SCORE_THRESHOLD", "RERANKER_DEVICE", "CITATION_SUPPORT_THRESHOLD",
    "RAG_ANSWER_CACHE_ENABLED",
    "MULTI_QUERY_MODE", "MULTI_QUERY_COUNT", "MULTI_QUERY_TEMPERATURE",
    "MULTI_QUERY_MAX_TOKENS", "MULTI_QUERY_TOP_K_PER", "MULTI_QUERY_DEDUP",
    "MULTI_QUERY_SIMILARITY", "MULTI_QUERY_MIN_LENGTH",
    "ADAPTIVE_CLUSTER_THRESHOLD", "ADAPTIVE_MAX_CLUSTER_DOCS",
    "ADAPTIVE_RETRIEVAL_ENABLED",
    "ADAPTIVE_MIN_CHUNKS", "ADAPTIVE_K_STEPS",
    "KNOWN_PERSON_NAMES", "DEFAULT_KEYWORDS", "SIGNAL_RULES",
    "DOC_TYPE_RULES", "DOMAIN_RULES", "blacklist",
    "SUMMARY_MAX_LENGTH", "TIME_PATTERNS",
    "RERANKER_THRESHOLD", "ENABLE_PLAN_CRITIQUE", "ENABLE_RESOURCE_MONITOR",
    # memory
    "ENABLE_MEMORY", "ENABLE_HISTORY_AWARE_RETRIEVAL",
    "SHORT_TERM_MAX_MESSAGES", "SESSION_MAX_MESSAGES",
    "CONTEXT_L2_SUMMARY_MIN_DELTA_MESSAGES",
    "ENABLE_LONG_TERM_MEMORY", "L3_PII_FILTER_ENABLED",
    "L3_DEDUP_COSINE_THRESHOLD", "L3_SUPERSEDE_THRESHOLD",
    "MEMORY_ORIGIN_EXPLICIT", "MEMORY_ORIGIN_INFERRED", "MEMORY_ORIGIN_LEGACY",
    "MEMORY_EXPLICIT_DEFAULT_CONFIDENCE", "MEMORY_INFERRED_DEFAULT_CONFIDENCE",
    "MEMORY_HEDGED_CONFIDENCE_CAP",
    "MEMORY_RETRIEVAL_CANDIDATES", "MEMORY_MAX_INJECTED",
    "MEMORY_MIN_RELEVANCE_SCORE", "MEMORY_GLOBAL_KEY_PREFIXES",
    "MEMORY_MAX_GLOBAL_PREFERENCES",
    "MEMORY_ASYNC_POOL_SIZE", "MEMORY_ASYNC_MAX_OVERFLOW",
    # storage
    "STORAGE_CHROMA_PATH", "STORAGE_BM25_DIR", "STORAGE_DOCS_DIR",
    "STORAGE_DOC_REGISTRY",
    # cleaner/filter
    "CLEAN_REMOVE_CONTROL_CHARS", "CLEAN_NORMALIZE_FULLWIDTH",
    "CLEAN_MERGE_BLANK_LINES", "CLEAN_STRIP_HTML",
    "CLEAN_REMOVE_PDF_HEADERS", "CLEAN_REMOVE_PDF_FOOTERS",
    "CLEAN_URL_ACTION", "CLEAN_EMAIL_ACTION",
    "FILTER_MIN_CHUNK_LENGTH", "FILTER_MAX_SYMBOL_RATIO",
    "FILTER_MIN_CHINESE_RATIO", "FILTER_SIMHASH_THRESHOLD",
    "FILTER_ENABLE_PII_MASK",
    # financial tables
    "FINANCIAL_TABLE_ROWS_PER_CHUNK",
    "FINANCIAL_MAX_CHUNKS_PER_DOC",
    "FINANCIAL_PII_MASK_FORCE",
    "FINANCIAL_SQL_BYPASS_ENABLED",
    "FINANCIAL_METRIC_PATTERNS",
    "FINANCIAL_NUMERIC_CONDITION_RE",
    "FINANCIAL_NUMERIC_CONDITION_RE_LTE",
    "FINANCIAL_PII_PATTERNS",
    # faithfulness
    "ENABLE_FAITHFULNESS", "FAITHFULNESS_SKIP_THRESHOLD", "NLI_USE_LLM",
    # email
    "SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "SMTP_FROM",
    "EMAIL_ENGINE", "AGENTLY_BIN", "AGENTLY_WATCH_MAX_SECONDS",
    # customer service
    "CS_ENABLED", "CS_CONFIRMATION_TTL_SECONDS", "CS_HANDOFF_TIMEOUT_SECONDS",
    "CS_MAX_CONFIRMATION_RETRIES", "CS_HIGH_RISK_ACTIONS", "CS_CRITICAL_ACTIONS",
    "CS_KNOWLEDGE_BASES", "COMPLAINT_PATTERNS", "CS_DOMAIN_KEYWORDS",
    "CS_DOMAIN_PATTERNS", "CS_RULE_MIN_HITS",
    "CS_CONFIDENCE_ANSWER", "CS_CONFIDENCE_CAUTIOUS",
    # CS Graph 独立架构（Phase 0）
    "CS_GRAPH_ENABLED", "CS_EXPERT_MAX_LOOPS", "CS_SUPERVISOR_LLM_ENABLED",
    "CS_SUPERVISOR_LLM_TIMEOUT_MS", "CS_CHECKPOINTER_ENABLED", "CS_GRAPH_RECURSION_LIMIT",
    # redis
    "REDIS_ENABLED", "REDIS_URL", "REDIS_KEY_PREFIX",
    "REDIS_MAX_CONNECTIONS", "REDIS_SOCKET_TIMEOUT",
    # observability
    "TRACE_PII_MASKING_ENABLED", "TRACE_DETAIL_LEVEL",
    "TRACE_SAMPLING_RATE", "TRACE_PG_MIRROR_ENABLED",
]

def __getattr__(name: str):
    # PEP 562 惰性转发：EVAL_DEVICE 的 auto 解析需要 import torch（~6s），
    # 不能在包导入期做（backend.config 在几乎所有模块的导入链上）。
    # 真正要用设备的代码请优先调 backend.config.llm.resolve_eval_device()。
    if name == "EVAL_DEVICE":
        from backend.config.llm import resolve_eval_device
        return resolve_eval_device()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
