"""config — 配置管理（按模块拆分）

.env 加载策略: 优先项目根目录 agent/.env，其次 backend/.env（无论 CWD 在哪）。
子模块（database/llm/rag/...）中的 load_dotenv() 不会被后加载的 .env 值
覆盖（override=False），因此只需一份配置。
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# 计算项目根目录: config/__init__.py → backend/config/ → backend/ → agent/
_ROOT = Path(__file__).resolve().parent.parent.parent
_BACKEND_DIR = _ROOT / "backend"
# 必须在下方读取任何 os.getenv 之前加载（否则 API_KEY/ALLOW_UNAUTHENTICATED 等
# 会拿到未填充的空值，导致 auth 中间件误判 fail-closed）。override=False：
# 先加载的根 .env 优先，子模块的 load_dotenv() 不会覆盖。
for _env_path in (_ROOT / ".env", _BACKEND_DIR / ".env"):
    if _env_path.exists():
        load_dotenv(_env_path)

# 运行环境（fail-safe: 无法识别时按 production 处理，拒绝降级到宽松策略）
_VALID_ENVIRONMENTS = {"development", "testing", "staging", "production"}
ENVIRONMENT = os.getenv("ENVIRONMENT", "development").strip().lower()
if ENVIRONMENT not in _VALID_ENVIRONMENTS:
    ENVIRONMENT = "production"

# 并发控制
MAX_CONCURRENT_REQUESTS = int(os.getenv("MAX_CONCURRENT_REQUESTS", "5"))
# 优先级排队：槽位满时高优先级请求（对话）进等待队列而不是立刻 503，
# 低优先级（上传/重索引/导出）几乎不等待直接拒绝。0 表示禁用排队（恢复纯 503）。
CONCURRENCY_QUEUE_TIMEOUT = float(os.getenv("CONCURRENCY_QUEUE_TIMEOUT", "10"))

# 安全
API_KEY = os.getenv("API_KEY", "")
# 显式豁免认证（仅限本地开发调试；生产环境禁止开启）
ALLOW_UNAUTHENTICATED = os.getenv("ALLOW_UNAUTHENTICATED", "false").strip().lower() in ("1", "true", "yes")
CORS_ORIGINS = os.getenv("CORS_ORIGINS", "http://localhost:3000")

# SQL 数据安全（P1-11）
# 信任网关注入的用户身份头：仅当反向代理/网关已完成认证并注入该头时开启。
# 开启后 /sql 路由从该头推导 current_user_id（行级安全参数），忽略请求体中的同名
# 字段（客户端不可伪造）；关闭时 user_id 恒为 None。
TRUST_USER_HEADER = os.getenv("TRUST_USER_HEADER", "false").strip().lower() in ("1", "true", "yes")
USER_ID_HEADER = os.getenv("USER_ID_HEADER", "X-User-Id")
# 行级安全总开关：默认关闭（Demo 查询不携带用户上下文，严格模式会全部拒绝）。
# 生产开启后，schema_config.row_security 中配置的表将强制按用户隔离。
SQL_ROW_SECURITY_ENABLED = os.getenv("SQL_ROW_SECURITY_ENABLED", "false").strip().lower() in ("1", "true", "yes")

# 报告
REPORT_SNAPSHOT_DAYS = int(os.getenv("REPORT_SNAPSHOT_DAYS", "30"))

# SMTP
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.qq.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_FROM = os.getenv("SMTP_FROM", SMTP_USER)

# Tool 审批门（写操作工具的 human-in-the-loop）
# required: 写操作需人工审批后执行（默认，企业安全基线）
# auto:     跳过审批直接执行（仅本地开发调试）
TOOL_APPROVAL_MODE = os.getenv("TOOL_APPROVAL_MODE", "required").strip().lower()
if TOOL_APPROVAL_MODE not in ("required", "auto"):
    TOOL_APPROVAL_MODE = "required"
# 已批准审批单的有效期（秒）：批准后需在 TTL 内重试相同操作才放行
TOOL_APPROVAL_TTL_SECONDS = int(os.getenv("TOOL_APPROVAL_TTL_SECONDS", "600"))

# MCP 工具调用超时（秒）— manager.route 无超时会挂死协议端点
MCP_TOOL_TIMEOUT = int(os.getenv("MCP_TOOL_TIMEOUT", "60"))

# 主图 LangGraph 保护
# 递归上限：supervisor 最多 10 轮 × (调度+执行) + 规划/审查/汇总 ≈ 25 超步，
# 取 80 留余量（超限 LangGraph 抛 GraphRecursionError 而非静默挂起）
MAIN_GRAPH_RECURSION_LIMIT = int(os.getenv("MAIN_GRAPH_RECURSION_LIMIT", "80"))
# 主图 checkpointer（默认关：开启后 request_context 以 checkpoint 安全 dict 进状态，
# Send 并行分支的流式/trace 绑定降级 — 见 orchestration/request_context.py）
MAIN_GRAPH_CHECKPOINTER_ENABLED = os.getenv("MAIN_GRAPH_CHECKPOINTER_ENABLED", "false").strip().lower() in ("1", "true", "yes")

# 通用 settings
from backend.config.settings import (
    LOG_LEVEL,
    LOG_FILE,
    OVERALL_REQUEST_TIMEOUT,
)
# 数据库
from backend.config.database import (
    RAG_DATA_DIR,
    CHUNK_STORE_PATH,
    BM25_INDEX_DIR,
    CHROMA_PATH,
    DOC_DB_PATH,
    DOCS_DIRECTORY,
    DOC_REGISTRY_PATH,
    DOC_OPERATION_LOG_PATH,
    ENABLE_INCREMENTAL_INDEX,
    DB_CONFIG,
    MEMORY_DB_CONFIG,
    BUSINESS_DB_CONFIG,
    BUSINESS_DB_READONLY_CONFIG,
    DB_POOL_MIN_CONN,
    DB_POOL_MAX_CONN,
    DB_CONNECT_TIMEOUT,
    DB_KEEPALIVES_IDLE,
)
# LLM
from backend.config.llm import (
    ENV_MODE,
    OLLAMA_ENABLED,
    OLLAMA_BASE_URL,
    OLLAMA_MODEL,
    OLLAMA_KEEP_ALIVE,
    EMBEDDING_MODEL,
    EMBEDDING_API_BASE,
    EMBEDDING_API_KEY,
    EMBEDDING_MODEL_PATH,
    RERANK_MODEL,
    RERANKER_MODEL_PATH,
    RERANK_TIMEOUT,
    EVAL_DEVICE,
    TOKEN_USAGE_LOG_PATH,
    EVAL_DATASET_PATH,
    LLM_MODEL,
    LLM_TEMPERATURE,
    LLM_CONTEXT_LENGTH,
    LLM_MAX_CONCURRENCY,
    LLM_REQUEST_TIMEOUT,
    ROUTER_LLM_TIMEOUT,
    ROUTER_LLM_MAX_TOKENS,
    PLANNER_LLM_MAX_TOKENS,
    ENABLE_TOKEN_STREAMING,
    LLM_STREAM_USAGE,
    DEEPSEEK_API_KEY,
    DEEPSEEK_API_BASE,
    MINIMAX_API_KEY,
    MINIMAX_API_BASE,
    QWEN_API_KEY,
    QWEN_API_BASE,
)
# RAG
from backend.config.rag import (
    CHUNK_SIZE,
    CHUNK_OVERLAP,
    POLICY_MAX_CHUNK_SIZE,
    PROJECT_CHUNK_SIZE,
    GENERAL_CHUNK_SIZE,
    GENERAL_CHUNK_OVERLAP,
    LEAF_CHUNK_TOKENS, PARENT_CHUNK_TOKENS, STRUCTURE_COMPLETE_THRESHOLD,
    ENABLE_SEMANTIC_CHUNKING, ENABLE_LLM_CHUNKING, LLM_CHUNK_MIN_CHARS,
    SEMANTIC_CHUNK_MIN_TOKENS, SEMANTIC_SIMILARITY_THRESHOLD,
    SEMANTIC_EMBED_BATCH_SIZE, SEMANTIC_EMBED_RETRY,
    EMBED_BATCH_SIZE,
    MAX_CHUNKS_PER_DOC,
    DEFAULT_KB_ID,
    BM25_SEARCH_K,
    HYBRID_SEARCH_K,
    RERANK_TOP_K,
    RERANK_SCORE_THRESHOLD,
    RERANKER_DEVICE,
    CITATION_SUPPORT_THRESHOLD,
    MULTI_QUERY_MODE,
    MULTI_QUERY_COUNT,
    MULTI_QUERY_TEMPERATURE,
    MULTI_QUERY_MAX_TOKENS,
    MULTI_QUERY_TOP_K_PER,
    MULTI_QUERY_DEDUP,
    MULTI_QUERY_SIMILARITY,
    MULTI_QUERY_MIN_LENGTH,
    EVIDENCE_TOKEN_BUDGET,
    ADAPTIVE_CLUSTER_THRESHOLD,
    ADAPTIVE_MAX_CLUSTER_DOCS,
    ADAPTIVE_RETRIEVAL_ENABLED,
    ADAPTIVE_MIN_CHUNKS, ADAPTIVE_K_STEPS,
    KNOWN_PERSON_NAMES,
    DEFAULT_KEYWORDS,
    SIGNAL_RULES,
    DOC_TYPE_RULES,
    DOMAIN_RULES,
    blacklist,
    SUMMARY_MAX_LENGTH,
    TIME_PATTERNS,
    # Faithfulness
    ENABLE_FAITHFULNESS,
    # Evidence Gate（P0）
    EVIDENCE_GATE_ENABLED,
    VEC_MIN_SCORE,
    DOC_TYPE_COVERAGE_REQUIRED,
    GATE_ENTITY_CHECK_ENABLED,
    RERANK_MIN_TOP1,
    RERANK_MIN_AVG,
    RERANK_MIN_GAP,
    RERANK_HIGH_RISK_MIN_TOP1,
    FAITHFULNESS_REJECT_SCORE,
    HIGH_RISK_REJECT_SCORE,
    SELF_CORRECTION_ENABLED,
    SELF_CORRECTION_MAX_RETRIES,
    KNOWLEDGE_GAP_MIN_OCCURRENCES,
    KNOWLEDGE_GAP_WINDOW_HOURS,
)
# Memory
from backend.config.memory import (
    ENABLE_MEMORY,
    ENABLE_HISTORY_AWARE_RETRIEVAL,
    SHORT_TERM_MAX_MESSAGES,
    HISTORY_TOKEN_BUDGET,
    SESSION_MAX_MESSAGES,
    ENABLE_LONG_TERM_MEMORY,
    L3_PII_FILTER_ENABLED,
    L3_DEDUP_COSINE_THRESHOLD,
    L3_SUPERSEDE_THRESHOLD,
    MEMORY_ASYNC_POOL_SIZE,
    MEMORY_ASYNC_MAX_OVERFLOW,
)
# Logging
from backend.config.logging import (
    LOG_LEVEL as LOG_LEVEL_CFG,  # alias 避免与 settings 冲突
    LOG_FILE as LOG_FILE_CFG,
)
# Storage
from backend.config.storage import (
    STORAGE_CHROMA_PATH,
    STORAGE_BM25_DIR,
    STORAGE_DOCS_DIR,
    STORAGE_DOC_REGISTRY,
)
# RAG 检索器
from backend.config.rag import (
    RERANKER_THRESHOLD,
    ENABLE_PLAN_CRITIQUE,
    ENABLE_RESOURCE_MONITOR,
)
# Cleaners
from backend.config.rag import (
    CLEAN_REMOVE_CONTROL_CHARS,
    CLEAN_NORMALIZE_FULLWIDTH,
    CLEAN_MERGE_BLANK_LINES,
    CLEAN_STRIP_HTML,
    CLEAN_REMOVE_PDF_HEADERS,
    CLEAN_REMOVE_PDF_FOOTERS,
    CLEAN_URL_ACTION,
    CLEAN_EMAIL_ACTION,
    FILTER_MIN_CHUNK_LENGTH,
    FILTER_MAX_SYMBOL_RATIO,
    FILTER_MIN_CHINESE_RATIO,
    FILTER_SIMHASH_THRESHOLD,
    FILTER_ENABLE_PII_MASK,
    # Financial tables
    FINANCIAL_TABLE_ROWS_PER_CHUNK,
    FINANCIAL_MAX_CHUNKS_PER_DOC,
    FINANCIAL_PII_MASK_FORCE,
    FINANCIAL_SQL_BYPASS_ENABLED,
    FINANCIAL_METRIC_PATTERNS,
    FINANCIAL_NUMERIC_CONDITION_RE,
    FINANCIAL_NUMERIC_CONDITION_RE_LTE,
    FINANCIAL_PII_PATTERNS,
)
# Faithfulness (NLI answer verification)
from backend.config.rag import (
    ENABLE_FAITHFULNESS, FAITHFULNESS_SKIP_THRESHOLD, NLI_USE_LLM,
)
# Input Guard（输入侧安全门禁）
from backend.config import guard  # noqa: F401 — 模块形式暴露（backend.config.guard.XXX）
# Customer Service（客服子系统）
from backend.config.customer_service import (
    CS_ENABLED,
    CS_CONFIRMATION_TTL_SECONDS,
    CS_HANDOFF_TIMEOUT_SECONDS,
    CS_MAX_CONFIRMATION_RETRIES,
    CS_HIGH_RISK_ACTIONS,
    CS_CRITICAL_ACTIONS,
    CS_KNOWLEDGE_BASES,
    COMPLAINT_PATTERNS,
    CS_DOMAIN_KEYWORDS,
    CS_DOMAIN_PATTERNS,
    CS_VECTOR_THRESHOLD,
    CS_RULE_MIN_HITS,
    CS_CONFIDENCE_ANSWER,
    CS_CONFIDENCE_CAUTIOUS,
    CS_ROUTER_INDEX_DIR,
    CS_GRAPH_ENABLED,
    CS_EXPERT_MAX_LOOPS,
    CS_SUPERVISOR_LLM_ENABLED,
    CS_SUPERVISOR_LLM_TIMEOUT_MS,
    CS_CHECKPOINTER_ENABLED,
    CS_GRAPH_RECURSION_LIMIT,
)
# Redis
from backend.config.redis import (
    REDIS_ENABLED,
    REDIS_URL,
    REDIS_KEY_PREFIX,
    REDIS_MAX_CONNECTIONS,
    REDIS_SOCKET_TIMEOUT,
)
# Observability (trace redaction / sampling / PG mirror)
from backend.config.observability import (
    TRACE_PII_MASKING_ENABLED,
    TRACE_DETAIL_LEVEL,
    TRACE_SAMPLING_RATE,
    TRACE_PG_MIRROR_ENABLED,
)

__all__ = [
    # environment
    "ENVIRONMENT",
    # settings
    "LOG_LEVEL", "LOG_FILE", "OVERALL_REQUEST_TIMEOUT",
    # sql 数据安全
    "TRUST_USER_HEADER", "USER_ID_HEADER", "SQL_ROW_SECURITY_ENABLED",
    # tool 审批门 / MCP / 主图保护
    "TOOL_APPROVAL_MODE", "TOOL_APPROVAL_TTL_SECONDS", "MCP_TOOL_TIMEOUT",
    "MAIN_GRAPH_RECURSION_LIMIT", "MAIN_GRAPH_CHECKPOINTER_ENABLED",
    # database
    "RAG_DATA_DIR", "CHUNK_STORE_PATH",
    "BM25_INDEX_DIR", "CHROMA_PATH", "DOC_DB_PATH", "DOCS_DIRECTORY",
    "DOC_REGISTRY_PATH", "DOC_OPERATION_LOG_PATH", "ENABLE_INCREMENTAL_INDEX", "DB_CONFIG", "MEMORY_DB_CONFIG", "BUSINESS_DB_CONFIG",
    "BUSINESS_DB_READONLY_CONFIG", "DB_POOL_MIN_CONN", "DB_POOL_MAX_CONN", "DB_CONNECT_TIMEOUT", "DB_KEEPALIVES_IDLE",
    # llm
    "LLM_MODEL", "LLM_TEMPERATURE", "LLM_CONTEXT_LENGTH", "LLM_MAX_CONCURRENCY",
    "LLM_REQUEST_TIMEOUT", "DEEPSEEK_API_KEY", "DEEPSEEK_API_BASE",
    "MINIMAX_API_KEY", "MINIMAX_API_BASE", "QWEN_API_KEY", "QWEN_API_BASE",
    "EMBEDDING_MODEL_PATH",
    "RERANKER_MODEL_PATH", "RERANK_TIMEOUT", "EVAL_DEVICE",
    # rag
    "CHUNK_SIZE", "CHUNK_OVERLAP", "PROJECT_CHUNK_SIZE",
    "POLICY_MAX_CHUNK_SIZE", "GENERAL_CHUNK_SIZE", "GENERAL_CHUNK_OVERLAP",
    "LEAF_CHUNK_TOKENS", "PARENT_CHUNK_TOKENS", "STRUCTURE_COMPLETE_THRESHOLD",
    "ENABLE_SEMANTIC_CHUNKING", "ENABLE_LLM_CHUNKING", "LLM_CHUNK_MIN_CHARS",
    "SEMANTIC_CHUNK_MIN_TOKENS", "SEMANTIC_SIMILARITY_THRESHOLD",
    "SEMANTIC_EMBED_BATCH_SIZE", "SEMANTIC_EMBED_RETRY",
    "EMBED_BATCH_SIZE",
    "MAX_CHUNKS_PER_DOC",
    "DEFAULT_KB_ID",
    "BM25_SEARCH_K", "HYBRID_SEARCH_K", "RERANK_TOP_K",
    "RERANK_SCORE_THRESHOLD", "RERANKER_DEVICE", "CITATION_SUPPORT_THRESHOLD",
    "MULTI_QUERY_MODE", "MULTI_QUERY_COUNT", "MULTI_QUERY_TEMPERATURE",
    "MULTI_QUERY_MAX_TOKENS", "MULTI_QUERY_TOP_K_PER", "MULTI_QUERY_DEDUP",
    "MULTI_QUERY_SIMILARITY", "MULTI_QUERY_MIN_LENGTH",
    "ADAPTIVE_CLUSTER_THRESHOLD", "ADAPTIVE_MAX_CLUSTER_DOCS",
    "ADAPTIVE_RETRIEVAL_ENABLED",
    "ADAPTIVE_MIN_CHUNKS", "ADAPTIVE_K_STEPS",
    "KNOWN_PERSON_NAMES", "DEFAULT_KEYWORDS", "SIGNAL_RULES",
    "DOC_TYPE_RULES", "DOMAIN_RULES", "blacklist",
    "SUMMARY_MAX_LENGTH", "TIME_PATTERNS",
    "RERANKER_THRESHOLD", "ENABLE_PLAN_CRITIQUE", "ENABLE_RESOURCE_MONITOR",
    # memory
    "ENABLE_MEMORY", "ENABLE_HISTORY_AWARE_RETRIEVAL",
    "SHORT_TERM_MAX_MESSAGES", "SESSION_MAX_MESSAGES",
    "ENABLE_LONG_TERM_MEMORY", "L3_PII_FILTER_ENABLED",
    "L3_DEDUP_COSINE_THRESHOLD", "L3_SUPERSEDE_THRESHOLD",
    "MEMORY_ASYNC_POOL_SIZE", "MEMORY_ASYNC_MAX_OVERFLOW",
    # storage
    "STORAGE_CHROMA_PATH", "STORAGE_BM25_DIR", "STORAGE_DOCS_DIR",
    "STORAGE_DOC_REGISTRY",
    # cleaner/filter
    "CLEAN_REMOVE_CONTROL_CHARS", "CLEAN_NORMALIZE_FULLWIDTH",
    "CLEAN_MERGE_BLANK_LINES", "CLEAN_STRIP_HTML",
    "CLEAN_REMOVE_PDF_HEADERS", "CLEAN_REMOVE_PDF_FOOTERS",
    "CLEAN_URL_ACTION", "CLEAN_EMAIL_ACTION",
    "FILTER_MIN_CHUNK_LENGTH", "FILTER_MAX_SYMBOL_RATIO",
    "FILTER_MIN_CHINESE_RATIO", "FILTER_SIMHASH_THRESHOLD",
    "FILTER_ENABLE_PII_MASK",
    # financial tables
    "FINANCIAL_TABLE_ROWS_PER_CHUNK",
    "FINANCIAL_MAX_CHUNKS_PER_DOC",
    "FINANCIAL_PII_MASK_FORCE",
    "FINANCIAL_SQL_BYPASS_ENABLED",
    "FINANCIAL_METRIC_PATTERNS",
    "FINANCIAL_NUMERIC_CONDITION_RE",
    "FINANCIAL_NUMERIC_CONDITION_RE_LTE",
    "FINANCIAL_PII_PATTERNS",
    # faithfulness
    "ENABLE_FAITHFULNESS", "FAITHFULNESS_SKIP_THRESHOLD", "NLI_USE_LLM",
    # email
    "SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "SMTP_FROM",
    # customer service
    "CS_ENABLED", "CS_CONFIRMATION_TTL_SECONDS", "CS_HANDOFF_TIMEOUT_SECONDS",
    "CS_MAX_CONFIRMATION_RETRIES", "CS_HIGH_RISK_ACTIONS", "CS_CRITICAL_ACTIONS",
    "CS_KNOWLEDGE_BASES", "COMPLAINT_PATTERNS", "CS_DOMAIN_KEYWORDS",
    "CS_DOMAIN_PATTERNS", "CS_VECTOR_THRESHOLD", "CS_RULE_MIN_HITS",
    "CS_CONFIDENCE_ANSWER", "CS_CONFIDENCE_CAUTIOUS", "CS_ROUTER_INDEX_DIR",
    # CS Graph 独立架构（Phase 0）
    "CS_GRAPH_ENABLED", "CS_EXPERT_MAX_LOOPS", "CS_SUPERVISOR_LLM_ENABLED",
    "CS_SUPERVISOR_LLM_TIMEOUT_MS", "CS_CHECKPOINTER_ENABLED", "CS_GRAPH_RECURSION_LIMIT",
    # redis
    "REDIS_ENABLED", "REDIS_URL", "REDIS_KEY_PREFIX",
    "REDIS_MAX_CONNECTIONS", "REDIS_SOCKET_TIMEOUT",
    # observability
    "TRACE_PII_MASKING_ENABLED", "TRACE_DETAIL_LEVEL",
    "TRACE_SAMPLING_RATE", "TRACE_PG_MIRROR_ENABLED",
]