-- agent_memory 库 schema dump

-- 生成于 scripts/export_schema_sql.py


CREATE SCHEMA IF NOT EXISTS "public";
CREATE SCHEMA IF NOT EXISTS "ai";

CREATE TABLE IF NOT EXISTS ai.agent_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id VARCHAR,
    user_query TEXT,
    task_type VARCHAR,
    status VARCHAR,
    created_at TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai.agent_trace (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_id INTEGER,
    node VARCHAR,
    input JSONB,
    output JSONB,
    duration NUMERIC,
    created_at TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id VARCHAR NOT NULL,
    role VARCHAR NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id VARCHAR NOT NULL,
    user_id VARCHAR NOT NULL,
    summary TEXT,
    context_summary TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (session_id)
);

CREATE TABLE IF NOT EXISTS public.memory_records (
    id UUID NOT NULL,
    user_id VARCHAR NOT NULL,
    session_id VARCHAR NOT NULL,
    memory_type VARCHAR NOT NULL,
    content TEXT NOT NULL,
    embedding BYTEA,
    importance_score DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    confidence_score DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    access_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    last_access_at TIMESTAMP,
    expire_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT true,
    superseded_by UUID,
    PRIMARY KEY (id)
);


-- 序列（serial 主键配套）
CREATE SEQUENCE IF NOT EXISTS ai.agent_tasks_id_seq OWNED BY ai.agent_tasks.id;
CREATE SEQUENCE IF NOT EXISTS ai.agent_trace_id_seq OWNED BY ai.agent_trace.id;
CREATE SEQUENCE IF NOT EXISTS public.chat_messages_id_seq OWNED BY public.chat_messages.id;
CREATE SEQUENCE IF NOT EXISTS public.chat_sessions_id_seq OWNED BY public.chat_sessions.id;

-- 索引（非 PK/UK）