-- agent_business 库 schema dump

-- 生成于 scripts/export_schema_sql.py


CREATE SCHEMA IF NOT EXISTS "product";
CREATE SCHEMA IF NOT EXISTS "order";
CREATE SCHEMA IF NOT EXISTS "inventory";
CREATE SCHEMA IF NOT EXISTS "customer";
CREATE SCHEMA IF NOT EXISTS "crawler";
CREATE SCHEMA IF NOT EXISTS "finance";

CREATE TABLE IF NOT EXISTS crawler.competitor_price (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id INTEGER,
    price NUMERIC,
    discount NUMERIC,
    crawl_time TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS crawler.competitor_products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    platform VARCHAR,
    brand VARCHAR,
    product_name VARCHAR,
    category VARCHAR,
    url VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS crawler.product_reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id INTEGER,
    rating INTEGER,
    review_text TEXT,
    sentiment VARCHAR,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS customer.customer_behavior (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id INTEGER,
    event_type VARCHAR,
    product_id INTEGER,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS customer.customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR,
    gender VARCHAR,
    level VARCHAR,
    register_time TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS finance.daily_profit (
    date DATE NOT NULL,
    revenue NUMERIC,
    cost NUMERIC,
    profit NUMERIC,
    PRIMARY KEY (date)
);

CREATE TABLE IF NOT EXISTS finance.expenses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR,
    amount NUMERIC,
    date DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id INTEGER,
    warehouse_id INTEGER,
    stock_quantity INTEGER DEFAULT 0,
    safety_stock INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.purchase_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    supplier_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    status VARCHAR,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.warehouses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR,
    location VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "order".order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    price NUMERIC,
    cost NUMERIC,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "order".orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_no VARCHAR NOT NULL,
    customer_id INTEGER,
    total_amount NUMERIC,
    status VARCHAR,
    payment_status VARCHAR,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (order_no)
);

CREATE TABLE IF NOT EXISTS "order".refunds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id INTEGER,
    product_id INTEGER,
    refund_amount NUMERIC,
    reason VARCHAR,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product.categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR NOT NULL,
    parent_id INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product.product_tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id INTEGER,
    tag VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product.products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku VARCHAR NOT NULL,
    product_name VARCHAR NOT NULL,
    category_id INTEGER,
    brand VARCHAR,
    cost_price NUMERIC,
    sale_price NUMERIC,
    status VARCHAR DEFAULT 'active'::character varying,
    created_at TIMESTAMP DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (sku)
);


-- 序列（serial 主键配套）
CREATE SEQUENCE IF NOT EXISTS crawler.competitor_price_id_seq OWNED BY crawler.competitor_price.id;
CREATE SEQUENCE IF NOT EXISTS crawler.competitor_products_id_seq OWNED BY crawler.competitor_products.id;
CREATE SEQUENCE IF NOT EXISTS crawler.product_reviews_id_seq OWNED BY crawler.product_reviews.id;
CREATE SEQUENCE IF NOT EXISTS customer.customer_behavior_id_seq OWNED BY customer.customer_behavior.id;
CREATE SEQUENCE IF NOT EXISTS customer.customers_id_seq OWNED BY customer.customers.id;
CREATE SEQUENCE IF NOT EXISTS finance.expenses_id_seq OWNED BY finance.expenses.id;
CREATE SEQUENCE IF NOT EXISTS inventory.inventory_id_seq OWNED BY inventory.inventory.id;
CREATE SEQUENCE IF NOT EXISTS inventory.purchase_orders_id_seq OWNED BY inventory.purchase_orders.id;
CREATE SEQUENCE IF NOT EXISTS inventory.warehouses_id_seq OWNED BY inventory.warehouses.id;
CREATE SEQUENCE IF NOT EXISTS order.order_items_id_seq OWNED BY order.order_items.id;
CREATE SEQUENCE IF NOT EXISTS order.orders_id_seq OWNED BY order.orders.id;
CREATE SEQUENCE IF NOT EXISTS order.refunds_id_seq OWNED BY order.refunds.id;
CREATE SEQUENCE IF NOT EXISTS product.categories_id_seq OWNED BY product.categories.id;
CREATE SEQUENCE IF NOT EXISTS product.product_tags_id_seq OWNED BY product.product_tags.id;
CREATE SEQUENCE IF NOT EXISTS product.products_id_seq OWNED BY product.products.id;

-- 索引（非 PK/UK）
CREATE INDEX idx_comp_price_time ON crawler.competitor_price USING btree (crawl_time);
CREATE INDEX idx_behavior_customer ON customer.customer_behavior USING btree (customer_id);
CREATE INDEX idx_inv_product ON inventory.inventory USING btree (product_id);
CREATE INDEX idx_oi_product ON "order".order_items USING btree (product_id);
CREATE INDEX idx_orders_created ON "order".orders USING btree (created_at);
CREATE INDEX idx_orders_status ON "order".orders USING btree (status);
CREATE INDEX idx_refunds_product ON "order".refunds USING btree (product_id);
CREATE INDEX idx_tags_product ON product.product_tags USING btree (product_id);
CREATE INDEX idx_products_category ON product.products USING btree (category_id);
CREATE INDEX idx_products_created ON product.products USING btree (created_at);