"""export_schema_sql.py — 从 information_schema / pg_catalog 生成两库的 schema-only SQL

补齐 /agent 库之前没有迁移脚本的缺失：让你能跨环境重建 memory 库结构。
"""
import os, psycopg2
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

ROOT = dict(host=os.getenv('PGHOST','localhost'),
            port=int(os.getenv('PGPORT','5432')),
            user=os.getenv('PGUSER','postgres'),
            password=os.getenv('PGPASSWORD',''))


def _list_objects(cur, target_schemas: set[str]) -> list:
    """按创建顺序返回 (schema, name, kind, ddl) 四元组。"""
    # 1) tables + views
    cur.execute("""
        SELECT table_schema, table_name, table_type
        FROM information_schema.tables
        WHERE table_schema = ANY(%s)
        ORDER BY table_schema, table_name
    """, (list(target_schemas),))
    items = []
    for sch, tbl, kind in cur.fetchall():
        items.append((sch, tbl, kind, None))
    return items


def _fetch_ddl(cur, sch: str, tbl: str) -> str:
    """从 pg_class / pg_attribute / pg_constraint 构造 CREATE TABLE 语句。

    pg_dump 不可用，但 psycopg2 + pg_catalog 完全可以重建等价 DDL。
    为简化输出：用 'CREATE TABLE IF NOT EXISTS' + 列定义 + 主键 + 简单索引。
    """
    # 1) 列
    cur.execute("""
        SELECT a.attname, a.atttypid, a.attnotnull,
               pg_get_expr(d.adbin, d.adrelid) AS default_expr,
               t.typname
        FROM pg_attribute a
        JOIN pg_type t ON t.oid = a.atttypid
        LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relname = %s
          AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum
    """, (sch, tbl))
    cols = cur.fetchall()
    if not cols:
        return ''

    # 类型简化映射
    TYPE_MAP = {
        'int4': 'INTEGER', 'int8': 'BIGINT', 'int2': 'SMALLINT',
        'text': 'TEXT', 'varchar': 'VARCHAR', 'bool': 'BOOLEAN',
        'timestamp': 'TIMESTAMP', 'timestamptz': 'TIMESTAMP',
        'date': 'DATE', 'jsonb': 'JSONB', 'numeric': 'NUMERIC',
        'float4': 'REAL', 'float8': 'DOUBLE PRECISION', 'uuid': 'UUID',
        'serial': 'SERIAL',  'bytea': 'BYTEA',
    }

    def map_type(name):
        return TYPE_MAP.get(name, name.upper())

    # 收集 IDENTITY 列（attidentity 列在 pg_attrdef 没有 default）
    identity_cols = set()
    cur.execute("""
        SELECT a.attname
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname=%s AND c.relname=%s
          AND a.attidentity IN ('a','d')  -- always / by default
    """, (sch, tbl))
    for (col,) in cur.fetchall():
        identity_cols.add(col)

    lines = []
    for name, _typid, notnull, default, typname in cols:
        # 1) IDENTITY 列：dump 直接保留 IDENTITY 字样
        if name in identity_cols:
            ty = 'INTEGER'
            nn = ' NOT NULL' if notnull else ''
            lines.append(f'    {name} {ty} GENERATED BY DEFAULT AS IDENTITY{nn}')
            continue
        # 2) SERIAL/序列：default 含 nextval —— 也用 IDENTITY 替换
        if default and 'nextval' in default.lower():
            ty = 'INTEGER'
            nn = ' NOT NULL' if notnull else ''
            lines.append(f'    {name} {ty} GENERATED BY DEFAULT AS IDENTITY{nn}')
            continue
        ty = map_type(typname.split('_')[0])
        nn = ' NOT NULL' if notnull else ''
        df = f' DEFAULT {default}' if default else ''
        lines.append(f'    {name} {ty}{nn}{df}')

    # 主键
    cur.execute("""
        SELECT a.attname
        FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = ANY(con.conkey)
        WHERE n.nspname=%s AND c.relname=%s AND con.contype='p'
        ORDER BY array_position(con.conkey, a.attnum)
    """, (sch, tbl))
    pks = [r[0] for r in cur.fetchall()]
    if pks:
        lines.append(f'    PRIMARY KEY ({", ".join(pks)})')

    # 唯一约束
    cur.execute("""
        SELECT pg_get_constraintdef(con.oid)
        FROM pg_constraint con
        JOIN pg_class c ON c.oid = con.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname=%s AND c.relname=%s AND con.contype='u'
    """, (sch, tbl))
    for (defn,) in cur.fetchall():
        lines.append(f'    {defn}')

    table_kind = 'TABLE'
    quoted = '"' + sch + '".' if sch != 'public' and '-' not in sch else ''
    if sch == 'order':
        quoted = '"order".'
    else:
        quoted = f'{sch}.'

    return f"CREATE TABLE IF NOT EXISTS {quoted}{tbl} (\n" + ",\n".join(lines) + "\n);\n"


def _fetch_indexes(cur, sch: str, tbl: str) -> list:
    cur.execute("""
        SELECT indexname, indexdef
        FROM pg_indexes
        WHERE schemaname=%s AND tablename=%s
          AND indexname NOT IN (
              SELECT constraint_name FROM information_schema.table_constraints
              WHERE table_schema=%s AND table_name=%s
          )
    """, (sch, tbl, sch, tbl))
    return [(name, defn) for name, defn in cur.fetchall()]


def _fetch_sequences(cur, target_schemas: list[str]) -> list:
    """拉所有与目标表相关的 SERIAL 序列，并在 Python 端构造 CREATE 语句。"""
    cur.execute("""
        SELECT n.nspname, s.relname, t.relname
        FROM pg_class s
        JOIN pg_namespace n ON n.oid = s.relnamespace
        JOIN pg_depend d  ON d.objid = s.oid AND d.classid = 'pg_class'::regclass
        JOIN pg_class t   ON t.oid = d.refobjid AND t.relkind='r'
        JOIN pg_namespace tn ON tn.oid = t.relnamespace
        WHERE s.relkind='S'
          AND tn.nspname = ANY(%s)
        ORDER BY n.nspname, s.relname
    """, (target_schemas,))
    seqs = []
    for sch, seq_name, tbl in cur.fetchall():
        quoted_sch = f'"{sch}"' if not sch.islower() else sch
        ddl = (f'CREATE SEQUENCE IF NOT EXISTS {quoted_sch}.{seq_name} '
               f'OWNED BY {quoted_sch}.{tbl}.id;')
        seqs.append((sch, seq_name, ddl))
    return seqs


def _emit_sql(dbname: str, target_schemas: list[str], out_path: str):
    lines = [f'-- {dbname} 库 schema dump\n',
             f'-- 生成于 scripts/export_schema_sql.py\n',
             '']

    conn = psycopg2.connect(dbname=dbname, **ROOT)
    cur = conn.cursor()

    # CREATE SCHEMA
    for sch in target_schemas:
        lines.append(f'CREATE SCHEMA IF NOT EXISTS "{sch}";')
    lines.append('')

    items = _list_objects(cur, set(target_schemas))
    for sch, tbl, kind, _ in items:
        ddl = _fetch_ddl(cur, sch, tbl)
        if ddl:
            lines.append(ddl)

    # 序列（CREATE SEQUENCE IF NOT EXISTS ... OWNED BY ...id）
    seqs = _fetch_sequences(cur, target_schemas)
    if seqs:
        lines.append('\n-- 序列（serial 主键配套）')
        for sch, name, ddl in seqs:
            lines.append(ddl)

    # 索引
    lines.append('\n-- 索引（非 PK/UK）')
    for sch, tbl, _, _ in items:
        for name, defn in _fetch_indexes(cur, sch, tbl):
            lines.append(defn + ';')

    conn.close()
    open(out_path, 'w', encoding='utf-8').write('\n'.join(lines))
    size = os.path.getsize(out_path)
    print(f'[OK] {dbname}: {out_path} ({size} bytes, {len(items)} 张表)')


# === 1) agent_memory：public + ai schema ===
mem_path = os.path.join('backend','sql','migrations','002_agent_memory_schema.sql')
_emit_sql('agent_memory', ['public', 'ai'], mem_path)

# === 2) agent_business：6 业务 schema（不含 ai，已迁到 memory 库）===
biz_path = os.path.join('backend','sql','migrations','003_agent_business_schema.sql')
_emit_sql('agent_business', ['product', 'order', 'inventory', 'customer', 'crawler', 'finance'], biz_path)



# === 1) agent_memory：public + ai schema ===
mem_path = os.path.join('backend','sql','migrations','002_agent_memory_schema.sql')
_emit_sql('agent_memory', ['public', 'ai'], mem_path)

# === 2) agent_business：6 业务 schema（不含 ai，已迁到 memory 库）===
biz_path = os.path.join('backend','sql','migrations','003_agent_business_schema.sql')
_emit_sql('agent_business', ['product', 'order', 'inventory', 'customer', 'crawler', 'finance'], biz_path)
